language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
branches:
  only:
    - master
    - develop
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
deploy:
  provider: releases
  file_glob: true
  file: ./build/Release/*.zip
  skip_cleanup: true
  on:
    tags: true
